version: '3.5'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:11.21-alpine3.17
  app:
    image: my-node-app
    ports:
      - 13000:3000
    
